name: í…ŒìŠ¤íŠ¸ ë° ë¹Œë“œ

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "infra/jacoco-test-pr-branch" ]

jobs:
  test-build:
    runs-on: ubuntu-latest # ìš°ë¶„íˆ¬ ìµœì‹  ë²„ì „ì—ì„œ
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4 # í˜„ì¬ ë¸Œëœì¹˜ì˜ ì½”ë“œë¥¼ actions ì„œë²„ì— ì˜¬ë¦¬ê¸°
      - name: JAVA 17 ì„¸íŒ…
        uses: actions/setup-java@v4 # ìë°” ì„¸íŒ… actions
        with:
          java-version: '17' # 17ë²„ì „
          distribution: 'temurin' # JDK ë°°í¬íŒ temurinì´ ëŒ€ì¤‘ì 

      - name: Gradle ì„¸íŒ…
        uses: gradle/actions/setup-gradle@v4 # ë²„ì „ íƒœê·¸ë¥¼ ì‚¬ìš©í•˜ëŠ” ë°©ì‹. ìµœì‹  v4.x.x ë¦´ë¦¬ìŠ¤

      - name: Build with Gradle Wrapper
        run: chmod +x ./gradlew && ./gradlew build jacocoTestCoverageVerification

  coverage-report:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    needs: test-build   # test-buildì´ ë¨¼ì € ì„±ê³µí•´ì•¼ ì‹¤í–‰ë¨ (ì„ íƒì‚¬í•­)
    if: always()         # â— í•­ìƒ ì‹¤í–‰ë˜ë„ë¡ (buildê°€ ì‹¤íŒ¨í•´ë„ ì‹¤í–‰ë¨)
    steps:
      - uses: actions/checkout@v4
      - name: JAVA 17 ì„¸íŒ…
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle Wrapper
        run: chmod +x ./gradlew && ./gradlew jacocoTestReport

      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/jacocoHtml/index.html

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: '## ğŸ§ª Service Layer Code Coverage'
          update-comment: true

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('ì„œë¹„ìŠ¤ ë ˆì´ì–´ ì „ì²´ ì»¤ë²„ë¦¬ì§€ê°€ 80% ë¯¸ë§Œì…ë‹ˆë‹¤.')