name: í…ŒìŠ¤íŠ¸ ë° ë¹Œë“œ

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "infra/jacoco-test-pr-branch" ]

jobs:
  test-build:
    runs-on: ubuntu-latest # ìš°ë¶„íˆ¬ ìµœì‹  ë²„ì „ì—ì„œ
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4 # í˜„ì¬ ë¸Œëœì¹˜ì˜ ì½”ë“œë¥¼ actions ì„œë²„ì— ì˜¬ë¦¬ê¸°
      - name: JAVA 17 ì„¸íŒ…
        uses: actions/setup-java@v4 # ìë°” ì„¸íŒ… actions
        with:
          java-version: '17' # 17ë²„ì „
          distribution: 'temurin' # JDK ë°°í¬íŒ temurinì´ ëŒ€ì¤‘ì 

      - name: Gradle ì„¸íŒ…
        uses: gradle/actions/setup-gradle@v4 # ë²„ì „ íƒœê·¸ë¥¼ ì‚¬ìš©í•˜ëŠ” ë°©ì‹. ìµœì‹  v4.x.x ë¦´ë¦¬ìŠ¤

      - name: Build with Gradle Wrapper
        run: chmod +x ./gradlew && ./gradlew build --continue

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: '## ğŸ§ª Service Layer Code Coverage'
          update-comment: true
          debug-mode: false
          pass-emoji: ':white_check_mark:'
          fail-emoji: ':x:'

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('ì„œë¹„ìŠ¤ ë ˆì´ì–´ ì „ì²´ ì»¤ë²„ë¦¬ì§€ê°€ 80% ë¯¸ë§Œì…ë‹ˆë‹¤.')

#  review-bot:
#    if: github.event_name == 'pull_request'
#    runs-on: ubuntu-latest
#    needs: test-build
#
#    steps:
#      - uses: anc95/ChatGPT-CodeReview@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#          PROMPT: |
#            ë‹¹ì‹ ì€ ì‹œë‹ˆì–´ Java ë°±ì—”ë“œ ê°œë°œìì…ë‹ˆë‹¤.
#            ì•„ë˜ diff ë‚´ìš©ì„ ë¦¬ë·°í•˜ê³  ë‹¤ìŒ í•­ëª©ì„ ì§€ì í•˜ì„¸ìš”:
#            - ì ì¬ì ì¸ ë²„ê·¸ë‚˜ ì˜ˆì™¸ ê°€ëŠ¥ì„±
#            - ì˜ëª»ëœ ë¡œì§, ì„±ëŠ¥ ì´ìŠˆ
#            - ì½ê¸° ì–´ë ¤ìš´ ì½”ë“œ ë˜ëŠ” ë¦¬íŒ©í† ë§ í¬ì¸íŠ¸
#            - Clean Code / SOLID ì›ì¹™ ìœ„ë°˜
#            ë¬¸ì œê°€ ì—†ë‹¤ê³  íŒë‹¨ë˜ë©´ LGTM ì‘ì„±.
#          LANGUAGE: Korean
#          MODEL: gpt-4o
#          max_tokens: 2000



